# Generated by Django 4.2.18 on 2025-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question_bn',
            new_name='question_bng',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_hi',
            new_name='question_esp',
        ),
        migrations.AddField(
            model_name='faq',
            name='question_frn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ger',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
